### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by wereallmonks** [strapi/gatsby-source-strapi#153] opened 2020-10-09 19:00 UTC
**Describe the bug**
I am getting this error after switching my settings from my production environment using postgres and then to my dev environment using sqlite. Switching between the two was fine before, but I did update my node version. Not sure if that could have had an effect. I do have public permission, so I don't get what's happening here..

**Steps to reproduce the behavior**
gatsby develop

I then get:

info Starting to fetch data from Strapi - http://localhost:1337/announcements?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/players?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/basics?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/results?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/about?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/calendar?_limit=1000
success Fetched Strapi Data - 0.128s

 ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 500

System

Node.js version: 12.14.1
NPM version: 6.14.8
Strapi version: 3.1.0-alpha.1
Database: sqlite3
Operating system: Catalina 10.15.7

**Comment by jawadkc** [comment] 2020-10-12 10:36
@wereallmonks, i was facing something similar. For me it was postgres instance issue. The max number of connections limit was being reached. After adjusting the values for max_connections, autovacuum_max_workers, and max_worker_processes of postgres it worked for me.

Not sure if its the same issue and root cause for you.

**Comment by wereallmonks** [comment] 2020-10-12 22:59
Yeah, I don't think that's my issue because it doesn't work on sqlite. I think it's because I updated node... not sure. I think I may have to redo everything because I even have internal server issues when trying to delete pic that were uploaded using the Cloudinary plugin on Strapi... ugh so disappointed.

**Comment by wereallmonks** [comment] 2020-10-13 22:58
I kind of feel making any updates to Strapi makes everything buggy. Pretty disappointed in Strapi. May have to use a different CMS.

**Comment by paul-ebose** [comment] 2020-10-22 20:45
I think the problem may be from the backend. Gatsby usually gives more descriptive errors. A debugger, graphiql or logging stuff out to the console can help.

**Comment by remidej** [comment] 2021-07-27 10:35
I'm closing since it seems to be an error from your Strapi app, not from this plugin

**Closed by remidej** 2021-07-27 10:35 UTC
