### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by DaTurboD** [strapi/gatsby-source-strapi#241] opened 2021-07-08 16:57 UTC
When i want to fetch a collection type with a media field (single image) i am getting an error "EPERM: operation not permitted" after /when the plugin tries to fetch the strapi data.

```
V:\Websites\mxd.codes\site\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: EPERM: operation not permitted, lstat 'V:\...\site\.cache\caches\gatsby-source-strapi\tmp-843dc8684b18661da051b4217ba5f6e3.jpg'
    at Object.lstatSync (fs.js:1115:3)
    at Object.lstatSync (V:\...\site\node_modules\graceful-fs\polyfills.js:312:16)
    at Object.rimrafSync (V:\...\site\node_modules\fs-extra\lib\remove\rimraf.js:237:18)
    at WriteStream.<anonymous> (V:\...\site\node_modules\gatsby-source-strapi\node_modules\gatsby-core-utils\dist\fetch-remote-file.js:107:26)
    at WriteStream.emit (events.js:387:35)
    at finish (internal/streams/writable.js:657:10)
    at finishMaybe (internal/streams/writable.js:644:9)
    at internal/streams/writable.js:617:7
    at WriteStream._final (internal/fs/streams.js:315:3)
    at callFinal (internal/streams/writable.js:610:10)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4048,
  syscall: 'lstat',
  code: 'EPERM',
  path: 'V:\\...\\site\\.cache\\caches\\gatsby-source-strapi\\tmp-843dc8684b18661da051b4217ba5f6e3.jpg'
}
```

gatsby-config.js
```js

    {
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: 'https://strapiurl',
        collectionTypes: [
          "post",
        ],
        singleTypes: [
        ],
        queryLimit: 1000,
      },
    },
```

package.json
```.json
  "dependencies": {
    "gatsby": "^3.9.0",
    "gatsby-plugin-gatsby-cloud": "^2.8.1",
    "gatsby-plugin-image": "^1.9.0",
    "gatsby-plugin-manifest": "^3.8.0",
    "gatsby-plugin-offline": "^4.8.0",
    "gatsby-plugin-react-helmet": "^4.8.0",
    "gatsby-plugin-sharp": "^3.9.0",
    "gatsby-source-filesystem": "^3.9.0",
    "gatsby-source-strapi": "^1.0.2",
    "gatsby-transformer-sharp": "^3.9.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0"
  },
```

Is there any "workaround" for this error?

**Comment by franjorub** [comment] 2021-07-14 03:26
the same issue previously just deleting .cache and node modules fixes the issue now it doesn't work

**Comment by remidej** [comment] 2021-07-27 09:47
I'm closing this issue since it's the same as #243 

I'm happy to reopen it if you can provide a repo or clear steps to reproduce it

**Closed by remidej** 2021-07-27 09:47 UTC
