### ISSUE TITLE
updated_at field is not defined in static query when there are no records

### ISSUE THREAD

**Issue by anilsoniaurionpro** [strapi/gatsby-source-strapi#242] opened 2021-07-16 08:36 UTC
I'm using Gatsby + gatsby-source plugin + MySQL.
I have a simple model.

If there are records of that model, the sort with **`updated_at`** works fine in the static query in Gatbsy.
But if there are no records of that model, the **`updated_at`** is not defined, thus the build fails.

is there a workaround so that the build doesn't fail?

**Comment by remidej** [comment] 2021-07-22 14:24
Hello,

The problem is that Gatsby guesses a schema based on the data that it's given. If it's given no data, it has no way of knowing the property exists.

Unfortunately there isn't a fix for this right now. You can either migrate to gatsby-source-graphql, or wait a few months for the next major release that will fix this.

**Closed by remidej** 2021-07-22 14:24 UTC
