### ISSUE TITLE
i18n not supported (only default locale entries fetched)

### ISSUE THREAD

**Issue by 8byr0** [strapi/gatsby-source-strapi#192] opened 2021-04-26 13:22 UTC
**Plugin version**: 1.0.0-alpha
**strapi version**: 3.6.0

After upgrading strapi to 3.6.0 with i18n, gatsby front only fetches default locale entries. From strapi doc, locale has to be explicitely defined in request for non default locale like:
```bash
http://localhost:1337/mymodel?_limit=1000&_locale=all # appropriate request that returns all results in every language
```
instead of 
```bash
http://localhost:1337/mymodel?_limit=1000 # actual request made by the plugin
```

It would be interesting to have more options in plugin config like this:
```js
module.exports = {
  // ...
  plugins: [
    {
      // ...
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: STRAPI_URL,
        contentTypes: [
          // List of the Content Types that are not localized.
          { name: 'modelA', locales: ['fr', 'en'] },
          { name: 'modelB', locales: ['fr', 'en'] },
          { name: 'modelC' },
          { name: 'modelD' },
        ],
        queryLimit: 1000,
      },
    },
  ],
};
```

@alexandrebodin what are your thoughts on this topic? I can definitely make a PR for this but I'd prefer knowing your expectations first!

**Comment by alexandrebodin** [comment] 2021-04-26 14:11
Hi indeed we haven't added support for this. I think we should make this more generic somehow like specifying query parameters we pass instead of support on specific locales param as it won't scale for new plugins in the future. 


Maybe something along those lines 🤔 

```js
options: {
  contentTypes: [
    { name: 'xxx', api: {  qs: { _locale: 'all' } } },
    { name: 'xxx', api: {  qs: { _locale: 'en' } } }
  ]
}
```

**Comment by 8byr0** [comment] 2021-04-26 16:48
There we go: https://github.com/strapi/gatsby-source-strapi/pull/193

**Comment by prKrumm** [comment] 2021-05-03 09:16
how is it working for singleTypes?
`singleTypes: [
    { name: 'xxx', api: {  qs: { _locale: 'all' } } },
    { name: 'xxx', api: {  qs: { _locale: 'en' } } }
  ]`

is not working

**Comment by alexandrebodin** [comment] 2021-05-03 12:40
It isn't released yet :D will be this week

**Comment by Leviathan91** [comment] 2021-05-07 10:07
Is there any date? It's end of the week now :>

**Comment by alexandrebodin** [comment] 2021-05-07 12:10
> Is there any date? It's end of the week now :>

Will be released next week as we needed to check something before making the release

**Comment by Leviathan91** [comment] 2021-05-18 08:28
Sorry to bother again, there still seem to be problems? It's been postponed twice now. We are using this in production and really need the language feature - is there any workaround?

**Comment by alexandrebodin** [comment] 2021-05-18 08:44
it was released last week in https://github.com/strapi/gatsby-source-strapi/releases/tag/v1.0.0-alpha.1 have you tried upgrade to alpha.1 ?

**Comment by wooqash** [comment] 2021-05-26 04:54
Sorry guys, but I still see the problem with single types. When I'm fetching the data using Graphiql I get only the default lang, despite I have 3 different lang set (de-CH as default, en-GB, pl-PL)

"strapi": "3.6.2",
"gatsby": "^3.6.0",
"gatsby-source-strapi": "^1.0.1",

gatsby-config:
```
    {
      resolve: "gatsby-source-strapi",
      options: {
        apiURL: process.env.API_URL || "http://localhost:1337",
        collectionTypes: [
          { name: "article", api: { qs: { _locale: `all` } } },
          "category",
          "writer",
        ],
        singleTypes: [
          `homepage`,
          `global`,
          {
            name: `coming-soon`,
            api: { qs: { _locale: `all` } },
          },
        ],
        queryLimit: 1000,
      },
    },
```
query at GraphiQL:
```
query MyQuery {
    allStrapiComingSoon {
       nodes {
         locale
       }
   }
}
```
returns only:
```
"allStrapiComingSoon": {
      "nodes": [
        {
          "locale": "de-CH"
        }
      ]
}
```
Is something what I'm missed? Thanks in advance for every help

**Comment by Leviathan91** [comment] 2021-05-31 11:06
Is there any update on this?
I am encountering the same problem, and it seems the initial fetching does not work as expected.
I'll tell you why I think this. 
This is my config:
` collectionTypes: [
          {
            name: `Blogs`,
            api: { qs: { _locale: process.env.CURRENT_LANGUAGE } },
          },
          {
            name: `Testemonials`,
            api: { qs: { _locale: process.env.CURRENT_LANGUAGE } },
          },
          {
            name: `Press-Releases`,
            api: { qs: { _locale: process.env.CURRENT_LANGUAGE } },
          },
          {
            name: `Press-News-Articles`,
            api: { qs: { _locale: process.env.CURRENT_LANGUAGE } },
          },
          {
            name: `Logos`,
            api: { qs: { _locale: 'all' } },
          },
        ],`

**Comment by Leviathan91** [comment] 2021-05-31 11:10
Silly question, but have you published your single type in the different locales? And enabled the localization support inside strapi?

**Comment by victory-sokolov** [comment] 2021-05-31 17:38
I have exact same problem with single types, it only returns the default language.  
Localization support is enabled inside strapi

**Comment by wooqash** [comment] 2021-05-31 20:03
> Silly question, but have you published your single type in the different locales? And enabled the localization support inside strapi?

It's not so silly question, but yes I published all locales for this single type. Moreover if I request url with locale as a query string for example
`http://localhost:1337/coming-soon?_locale=pl-PL` or `http://localhost:1337/coming-soon?_locale=en-GB` its returns a valid data. I think the problem is somewhere at gatsby. Maybe at plugin `gatsby-source-strapi`?

**Comment by remidej** [comment] 2021-06-01 16:06
@wooqash @victory-sokolov thanks for pointing this out. It's true that the behavior of single types with i18n is more awkward.

You can make it work though. Try adding several entity definition objects for the same single type in your config, one for each locale (don't use "all"). Like this:

```js
singleTypes: [
  {
    name: 'global',
    api: {
      qs: {
        _locale: 'en'
      }
    },
  },
  {
    name: 'global',
    api: {
      qs: {
        _locale: 'fr'
      }
    },
  },
],
```

Gatsby will merge them together, so you can make a dynamic query like this:

```graphql
{
  strapiGlobal(locale: { eq: $locale }) {
    id
    locale
  }
}
```

I'll add an example to the readme

**Comment by wooqash** [comment] 2021-06-01 16:25
@remidej many thanks, it looks that this solution works. Finally, it returns values with all languages. One more question, is it a temporary workaround or rather we should use this solution within all single types?

**Comment by remidej** [comment] 2021-06-01 16:34
@wooqash I think we'll keep with this solution, so you can do this for all your single types. We don't want to add new breaking changes right now.

**Comment by wooqash** [comment] 2021-06-01 16:36
Ok, sure, thx for the clarification.

**Comment by remidej** [comment] 2021-06-03 13:45
I'm closing this issue since #225 added a readme example for i18n on single types as well

**Closed by remidej** 2021-06-03 13:45 UTC
