### ISSUE TITLE
Cannot query image from component field : Cannot query field "publicURL" on type "StrapiHomepageImg_descImage".

### ISSUE THREAD

**Issue by demiton** [strapi/gatsby-source-strapi#124] opened 2020-05-09 08:36 UTC
Hello, 
I've got an error `Cannot query field "publicURL" on type "StrapiHomepageImg_descImage".` when I tried to get  the  publicURL of an image component( with an image field and name field)
```
img_desc{
  image{
    publicURL
  }
   name
}
```
But it's not happened all the times. 
I thought it was a asynchronous problem. My server being not very fast, the response can be sometimes slower than usual.. 
So I checked the plugin , it seems that you forgot  `await` at 2 places, it should be `await extractFields(apiURL, store, cache, createNode, touchNode, auth, f)` to respect the asynchronous behavior.

https://github.com/strapi/gatsby-source-strapi/blob/2d5d641538c42d24dc2bf2c817139bdcc1f0e7e9/src/normalize.js#L18

https://github.com/strapi/gatsby-source-strapi/blob/2d5d641538c42d24dc2bf2c817139bdcc1f0e7e9/src/normalize.js#L69

I made the fix on a fork, and now everything works fine for me :)

Thank you very much for your fantastic Strapi !!

**Comment by demiton** [comment] 2020-05-18 20:31
Hello @Jaikant , 
you're right, I've just commit the fix. Because the await was present on my computer so I didnt take care of it...
Please try again and tell me :)

**Comment by Jaikant** [comment] 2020-05-19 06:23
@demiton I tried with your new commits, but all the data fetching fails. No nodes are fetched.

**Comment by demiton** [comment] 2020-05-19 16:16
@Jaikant , sorry for that , your issue is probably different than mine..

**Comment by radoslawhryciow** [comment] 2020-06-08 10:56
@demiton I've created local npm package for gatsby-source-strapi from your fork and it seems to be working as expected. Nice work! 

Could you please make pull request to strapi original repo from your fork? 

It would be great to have this working out of the box.

Thank you!

**Comment by samOpenforce** [comment] 2020-06-18 13:01
@demiton Amazing work! Thank you, you have just saved a project! I have done the same as @radoslawhryciow and created a local npm package which solves my issue.

Would be great to see this merged!

**Comment by radoslawhryciow** [comment] 2020-06-18 21:29
@samOpenforce :) 

@alexandrebodin What could I do to have these changes in the official package?

**Comment by alexandrebodin** [comment] 2020-06-19 07:30
@radoslawhryciow We will need a PR as we are still a small team and have to focus on the feature developement until we reach the right balance before moving on to the "SDK" stuff

**Comment by radoslawhryciow** [comment] 2020-06-19 07:39
@alexandrebodin ok, thanks.

@demiton is this ok for you that I will make PR with missing awaits?

**Comment by demiton** [comment] 2020-06-20 08:32
Hello,
Sorry for the delay, I was busy theses days.
@radoslawhryciow , happy to see that my post helps some else !
You can do make the PR of course :)
Thank you very much,
Cheers,

**Comment by demiton** [comment] 2020-06-30 14:18
Hello guys :)
@radoslawhryciow,  @alexandrebodin , finally is there any PR planned to fix this issue ?

**Comment by radoslawhryciow** [comment] 2020-06-30 14:24
@demiton I will create PR today.

**Comment by radoslawhryciow** [comment] 2020-07-02 07:26
@alexandrebodin PR is ready https://github.com/strapi/gatsby-source-strapi/pull/135

@demiton and others :) Please add your review to this PR - maybe this will speed up merging changes to master ! 

Thanks!

**Comment by radoslawhryciow** [comment] 2020-07-02 12:44
My PR fixing this issue was merged today. 

@alexandrebodin Thank you for merge. When my changes will be published to npm as a new package?

**Comment by alexandrebodin** [comment] 2020-07-02 13:25
I will be reviewing everything in one week and release a bit after

**Comment by demiton** [comment] 2020-07-04 12:11
Hello guys, 
sorry Im not agree with your PR #135, `extractFields` is defined as an async function `const extractFields = async...` , so you always need to put `await before` (the await is like then for promise). Because the function async function is  a promise as @alexandrebodin  saids, if it is inside a promise.all, you don't need await. But If after tests, @radoslawhryciow you see that the the `async` after map is needed, Im pretty sure you must put `await` before the function !

**Comment by radoslawhryciow** [comment] 2020-07-06 10:08
Hi @demiton,
you're right. ```extractFields``` is declared with the ```async``` keyword, we should call it with the ```await``` keyword. Without ```await``` it is still working correctly because of ```Promise.all```.

Anyway I would suggest to use ```await``` keyword here for code to be more self-documenting (extractFields is still async, could be declared in some other file etc.).

@alexandrebodin what do you think?

**Comment by alexandrebodin** [comment] 2020-07-06 12:28
Hi,

Doing 
```js
await Promise.all(arr.map(async () => await sth()))
```
is actually buggy. 

if you throw in the iterator function it will throw an unhandledRejection error because the map iterator is supposed to be sync

This code should look like

```js
await Promise.all(arr.map(() => aFunction()))

const aFunction =  async () => {}
```
you should not make the iterator function an async one as there is nothing to catch it if it throws.

**Comment by demiton** [comment] 2020-07-08 16:42
Hello,
@alexandrebodin , I'm ok with you. But @radoslawhryciow , did you said without `map(async()=>...` it is not working ? 
Sorry, I haven't the time to test right now, Im going to holidays..

**Comment by radoslawhryciow** [comment] 2020-07-08 17:00
@demiton 

```javascript
// #1 not working
field.map(async f =>
    extractFields(apiURL, store, cache, createNode, touchNode, auth, f)
)
```

```javascript
// #2 not working
field.map(f =>
    extractFields(apiURL, store, cache, createNode, touchNode, auth, f)
)
```

```javascript
// #3 working - currently in master branch
field.map(async f =>
    extractFields(apiURL, store, cache, createNode, touchNode, auth, f)
)
```

```javascript
// #4 working
field.map(async f =>
   await extractFields(apiURL, store, cache, createNode, touchNode, auth, f)
)
```

**Comment by hashinteractive** [comment] 2020-08-19 17:16
Subscribing to this as this is still throwing an error.

**Comment by nimrodshory** [comment] 2020-09-06 19:21
I am getting these errors `Cannot query field "publicURL" on type ...` when querying on an image field.
Sometime it happens and sometime it doesn't, sometimes it says I need to use `url` and sometimes `publicURL`.
Can't figure out why it happens or how to reproduce consistently.

**Comment by juanoa** [comment] 2021-01-13 12:30
Same problem, but only when I deploy it on Netlify.

```
strapiPost(slug: {eq: $slug}) {
      title
      content
      category {
          id
          slug
          title
      }
      coverPhoto {
        publicURL
      }
      book {
        title
        link
        description
        coverPhoto {
          publicURL
        }
      }
      seoDescription
      seoTitle
    }
```

**Comment by alexandrebodin** [comment] 2021-01-13 15:27
Hi @juanoa  what version are you working with ?

**Comment by juanoa** [comment] 2021-01-13 19:27
These are my dependencies:

("gatsby-source-strapi": "^0.0.12")

```json
"dependencies": {
    "bootstrap": "^4.5.3",
    "gatsby": "^2.26.1",
    "gatsby-image": "^2.5.0",
    "gatsby-plugin-google-gtag": "^2.5.0",
    "gatsby-plugin-manifest": "^2.6.1",
    "gatsby-plugin-offline": "^3.4.0",
    "gatsby-plugin-react-helmet": "^3.4.0",
    "gatsby-plugin-sharp": "^2.8.0",
    "gatsby-plugin-sitemap": "^2.9.0",
    "gatsby-source-filesystem": "^2.5.0",
    "gatsby-source-strapi": "^0.0.12",
    "gatsby-transformer-sharp": "^2.6.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-bootstrap": "^1.4.0",
    "react-cookie-consent": "^6.2.1",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.1.0",
    "react-markdown": "^5.0.3"
  }
```

**Comment by alexandrebodin** [comment] 2021-01-13 20:02
We release the v1 alpha you should test it it should fix your issue :) I hope to move it to stable once we have enough feedbacks :)

**Comment by juanoa** [comment] 2021-01-15 16:51
> We release the v1 alpha you should test it it should fix your issue :) I hope to move it to stable once we have enough feedbacks :)

Bug fixed at v1 alpha using the following query:
```
singleImage {
  localFile {
    publicURL
  }
}
```

Thanks!

**Closed** 2022-02-16 13:11 UTC
