### ISSUE TITLE
Support ImageSharp[gatsby-image]

### ISSUE THREAD

**Issue by sylvesteraswin** [strapi/gatsby-source-strapi#41] opened 2019-01-06 11:57 UTC
I am starting to use `Strapi` to create a photography portfolio site. I am uploading images using the image uploader.

I would like to use `gatsby-image` plugin for the images uploaded through `strapi`. Is it possible to add `gatsby-images` as part of this plugin?

**Comment by Turkyden** [comment] 2019-03-21 03:21
Me too, i have also meet this problem and unabled to fetch the image from strapi.
Duplicate of #

**Comment by fusioneery** [comment] 2019-03-26 09:07
+1.
For now, it works very strange: all images are cached and mixed up between content types.

**Comment by dkarski** [comment] 2019-06-05 13:06
+1

**Comment by dkarski** [comment] 2019-06-06 14:22
@sylvesteraswin @Turkyden @fusioneery 
Did you see workround with implemented by @ernest-okot
[5#issuecomment-399299309](https://github.com/strapi/gatsby-source-strapi/issues/5#issuecomment-399299309)

**Comment by dkarski** [comment] 2019-06-07 08:03
@sylvesteraswin I think you can use [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/) for your images.

> Depending on the gatsby starter you used, you may need to include gatsby-transformer-sharp and gatsby-plugin-sharp as well, and make sure they are installed and included in your gatsby-config.

In my case it's not work with `images` for the WYSWIG content, there gatsby can't transform images.

**Comment by Pedromigacz** [comment] 2021-02-15 19:22
Any progress on this issue? I'm trying to do exactly that, and have not found a solution yet

**Closed** 2022-02-16 13:12 UTC
