### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by franjorub** [strapi/gatsby-source-strapi#243] opened 2021-07-19 14:48 UTC
When I upload images in strapi I always deal with this and is randomly fixed but at first gatsby clean, remove .cache folder and remove node modules doesn't work

Error: EPERM: operation not permitted, lstat 'C:\Users\franj\Desktop\agencia\frontend\.cache\caches\gatsby-source-strapi\tmp-cb67ddcade195a5a1260c2d389fd832e.png'

  errno: -4048,
  syscall: 'lstat',
  code: 'EPERM',
  path: 'C:\\Users\\franj\\Desktop\\agencia\\frontend\\.cache\\caches\\gatsby-source-strapi\\tmp-cb67ddcade195a5a1260c2d389fd832e.png'

Windows 10
Gatsby 3.9.1
Gatsby cli 3.9.0
Strapi 3.6.5
"gatsby-source-strapi": "^1.0.1"

**Comment by remidej** [comment] 2021-07-27 09:43
> When I upload images in strapi I always deal with this and is randomly fixed

I sounds like your problem doesn't come from gatsby-source-strapi then.

It's probably related to your local environment, maybe the access permissions of your file system? Have you tried running chmod commands?

Either way I'm closing this issue, since it's not related to this plugin, and I can't reproduce your problem

**Closed by remidej** 2021-07-27 09:43 UTC

**Comment by codebucks27** [comment] 2021-12-06 07:18
> > When I upload images in strapi I always deal with this and is randomly fixed
> 
> I sounds like your problem doesn't come from gatsby-source-strapi then.
> 
> It's probably related to your local environment, maybe the access permissions of your file system? Have you tried running chmod commands?
> 
> Either way I'm closing this issue, since it's not related to this plugin, and I can't reproduce your problem

Hey, I have faced similar issue in the windows.

I have given all the permission to folders and subfolders too.
Tried to remove gatsby cache and also reinstall all the node_modules but this issue is still there.

First when I have uploaded few images on strapi and then when I try to use them in my gatsby project via gatsby develop command then it keeps showing "operation not permitted" error.

Like below👇
`Error: EPERM: operation not permitted, lstat '\\?\D:\Freelancing\Mistiqa-V-2.0\.cache\caches\gatsby-source-strapi\tmp-3bae77b109295f5250e620ffe721d42f.png'`

Let me know if someone can find any solution for this!😥

**Comment by thedivtagguy** [comment] 2021-12-11 06:10
> Let me know if someone can find any solution for this!😥
Were you able to resolve this? How?

**Comment by codebucks27** [comment] 2021-12-20 13:31
> > Let me know if someone can find any solution for this!😥
> 
> Were you able to resolve this? How?

No man. I don't know why nobody is taking any action to solve this.
I have 15 products on strapi and when I tried to upload few images (20-25mb) and then I can not start my development server.

In this error it couldn't find temporary image file because it might getting deleted.
when i unpublished few of my products then development server started running but that's not a solution.

I have installed WSL2 (windows subsystem for linux) where you can use linux files and binaries in windows without dual boot.
But still i'm facing issue in that too. Btw in WSL this permission error is gone.

**Comment by Hasnain-110** [comment] 2022-07-12 06:01
facing same issue

**Comment by codebucks27** [comment] 2022-07-12 11:29
> facing same issue

Have you tried using Linux or WSL2 (windows subsystem for linux) ?
